# Fine Print AI Promtail Configuration
# Log shipping configuration for all Fine Print AI services

server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: info

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    batchwait: 1s
    batchsize: 1048576
    backoff_config:
      min_period: 500ms
      max_period: 5m
      max_retries: 10
    timeout: 10s

scrape_configs:
  # Analysis Service Logs
  - job_name: analysis-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: analysis-service
          service: analysis
          environment: production
          __path__: /var/log/fineprintai/analysis/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            user_id: user_id
            request_id: request_id
            document_id: document_id
            analysis_duration: analysis_duration
            patterns_found: patterns_found
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          user_id:
          request_id:
      - output:
          source: message

  # Analytics Service Logs  
  - job_name: analytics-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: analytics-service
          service: analytics
          environment: production
          __path__: /var/log/fineprintai/analytics/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            user_id: user_id
            event_type: event_type
            metric_name: metric_name
            metric_value: metric_value
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          event_type:
      - output:
          source: message

  # Billing Service Logs
  - job_name: billing-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: billing-service
          service: billing
          environment: production
          __path__: /var/log/fineprintai/billing/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            user_id: user_id
            subscription_id: subscription_id
            payment_id: payment_id
            amount: amount
            currency: currency
            status: status
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          status:
      - output:
          source: message

  # Gateway Service Logs
  - job_name: gateway-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: gateway-service
          service: gateway
          environment: production
          __path__: /var/log/fineprintai/gateway/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            method: method
            url: url
            status_code: status_code
            response_time: response_time
            user_agent: user_agent
            ip_address: ip_address
            request_id: request_id
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          method:
          status_code:
      - output:
          source: message

  # Monitoring Service Logs
  - job_name: monitoring-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: monitoring-service
          service: monitoring
          environment: production
          __path__: /var/log/fineprintai/monitoring/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            alert_name: alert_name
            severity: severity
            service: service
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          severity:
      - output:
          source: message

  # Notification Service Logs
  - job_name: notification-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: notification-service
          service: notification
          environment: production
          __path__: /var/log/fineprintai/notification/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            user_id: user_id
            notification_type: notification_type
            delivery_status: delivery_status
            channel: channel
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          notification_type:
          delivery_status:
      - output:
          source: message

  # WebSocket Service Logs
  - job_name: websocket-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: websocket-service
          service: websocket
          environment: production
          __path__: /var/log/fineprintai/websocket/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            connection_id: connection_id
            user_id: user_id
            event_type: event_type
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          event_type:
      - output:
          source: message

  # NGINX Access Logs
  - job_name: nginx-access
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx-access
          service: nginx
          environment: production
          __path__: /var/log/nginx/access.log
    pipeline_stages:
      - regex:
          expression: '^(?P<remote_addr>\S+) - (?P<remote_user>\S+) \[(?P<time_local>[^\]]+)\] "(?P<method>\S+) (?P<url>\S+) (?P<protocol>\S+)" (?P<status>\d+) (?P<body_bytes_sent>\d+) "(?P<http_referer>[^"]*)" "(?P<http_user_agent>[^"]*)" "(?P<request_id>[^"]*)" (?P<response_time>\d+\.\d+)'
      - timestamp:
          source: time_local
          format: "02/Jan/2006:15:04:05 -0700"
      - labels:
          method:
          status:
      - output:
          source: message

  # NGINX Error Logs
  - job_name: nginx-error
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx-error
          service: nginx
          environment: production
          log_type: error
          __path__: /var/log/nginx/error.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}/\d{2}/\d{2} \d{2}:\d{2}:\d{2}) \[(?P<level>\w+)\] (?P<pid>\d+)#(?P<tid>\d+): (?P<message>.*)'
      - timestamp:
          source: timestamp
          format: "2006/01/02 15:04:05"
      - labels:
          level:
      - output:
          source: message

  # Kubernetes Pod Logs
  - job_name: kubernetes-pods
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels:
          - __meta_kubernetes_pod_controller_name
        regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
        action: replace
        target_label: __tmp_controller_name
      - source_labels:
          - __meta_kubernetes_pod_label_app_kubernetes_io_name
          - __meta_kubernetes_pod_label_app
          - __tmp_controller_name
          - __meta_kubernetes_pod_name
        regex: ^;*([^;]+)(;.*)?$
        action: replace
        target_label: app
      - source_labels:
          - __meta_kubernetes_pod_label_app_kubernetes_io_component
          - __meta_kubernetes_pod_label_component
        regex: ^;*([^;]+)(;.*)?$
        action: replace
        target_label: component
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: node_name
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        replacement: $1
        separator: /
        source_labels:
        - namespace
        - app
        target_label: job
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - action: replace
        replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        target_label: __path__
    pipeline_stages:
      - cri: {}
      - json:
          expressions:
            timestamp: time
            stream: stream
            message: log
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - output:
          source: message

  # System Logs
  - job_name: syslog
    static_configs:
      - targets:
          - localhost
        labels:
          job: syslog
          service: system
          environment: production
          __path__: /var/log/syslog
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\w+\s+\d+\s+\d{2}:\d{2}:\d{2}) (?P<hostname>\S+) (?P<service>\S+): (?P<message>.*)'
      - timestamp:
          source: timestamp
          format: "Jan 02 15:04:05"
      - labels:
          hostname:
          service:
      - output:
          source: message