version: '3.8'

services:
  temporal:
    image: temporalio/auto-setup:1.22.4
    container_name: temporal-server
    ports:
      - "7233:7233"
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=temporal-postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    depends_on:
      - temporal-postgresql
    networks:
      - temporal-network
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig

  temporal-postgresql:
    image: postgres:16-alpine
    container_name: temporal-postgresql
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    ports:
      - "5433:5432"
    networks:
      - temporal-network
    volumes:
      - temporal-postgresql-data:/var/lib/postgresql/data

  temporal-admin-tools:
    image: temporalio/admin-tools:1.22.4
    container_name: temporal-admin-tools
    stdin_open: true
    tty: true
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    networks:
      - temporal-network
    depends_on:
      - temporal

  temporal-ui:
    image: temporalio/ui:2.21.3
    container_name: temporal-ui
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    ports:
      - "8080:8080"
    networks:
      - temporal-network
    depends_on:
      - temporal

networks:
  temporal-network:
    driver: bridge
    name: temporal-network

volumes:
  temporal-postgresql-data:
    driver: local