apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-gateway
  namespace: fineprintai-gateway
  labels:
    app: redis-gateway
    component: cache
spec:
  serviceName: redis-gateway
  replicas: 1
  selector:
    matchLabels:
      app: redis-gateway
  template:
    metadata:
      labels:
        app: redis-gateway
        component: cache
    spec:
      securityContext:
        fsGroup: 999
        runAsUser: 999
        runAsNonRoot: true
      containers:
      - name: redis
        image: redis:7.2-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
          name: redis
        command:
        - redis-server
        - /etc/redis/redis.conf
        - --requirepass
        - $(REDIS_PASSWORD)
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: password
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis
        - name: redis-data
          mountPath: /data
        livenessProbe:
          exec:
            command:
            - redis-cli
            - --pass
            - $(REDIS_PASSWORD)
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - redis-cli
            - --pass
            - $(REDIS_PASSWORD)
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 5
          failureThreshold: 3
      volumes:
      - name: redis-config
        configMap:
          name: redis-config
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis-gateway
  namespace: fineprintai-gateway
  labels:
    app: redis-gateway
    component: cache
spec:
  selector:
    app: redis-gateway
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: fineprintai-gateway
data:
  redis.conf: |
    # Redis configuration for Kong Gateway
    bind 0.0.0.0
    port 6379
    
    # Memory management
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    
    # Persistence
    save 900 1
    save 300 10
    save 60 10000
    
    # Security
    protected-mode yes
    
    # Logging
    loglevel notice
    
    # Performance
    tcp-keepalive 300
    timeout 0
    
    # Append-only file
    appendonly yes
    appendfsync everysec
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: fineprintai-gateway
type: Opaque
data:
  password: ZmluZXByaW50YWktcmVkaXMtcGFzc3dvcmQtY2hhbmdlLW1l # base64 encoded, change in production