_format_version: "3.0"
_transform: true

services:
  - name: api-service
    url: http://api:8000
    routes:
      - name: api-route
        paths:
          - /api
        strip_path: true
        methods:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
          - OPTIONS

  - name: websocket-service
    url: http://websocket:8001
    routes:
      - name: websocket-route
        paths:
          - /ws
        strip_path: true

plugins:
  - name: cors
    config:
      origins:
        - "http://localhost:3003"
        - "http://localhost:3001"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - Authorization
      exposed_headers:
        - X-Auth-Token
      credentials: true
      max_age: 3600

  - name: rate-limiting
    config:
      minute: 100
      hour: 1000
      policy: local