# Comprehensive Service Accounts for Fine Print AI multi-environment setup

# Production Environment Service Accounts
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fineprintai-analysis
  namespace: fineprintai-prod
  labels:
    app.kubernetes.io/name: fineprintai
    app.kubernetes.io/component: analysis
    environment: production
automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fineprintai-websocket
  namespace: fineprintai-prod
  labels:
    app.kubernetes.io/name: fineprintai
    app.kubernetes.io/component: websocket
    environment: production
automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fineprintai-gateway
  namespace: fineprintai-prod
  labels:
    app.kubernetes.io/name: fineprintai
    app.kubernetes.io/component: gateway
    environment: production
automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fineprintai-notification
  namespace: fineprintai-prod
  labels:
    app.kubernetes.io/name: fineprintai
    app.kubernetes.io/component: notification
    environment: production
automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fineprintai-monitoring
  namespace: fineprintai-prod
  labels:
    app.kubernetes.io/name: fineprintai
    app.kubernetes.io/component: monitoring
    environment: production
automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fineprintai-database
  namespace: fineprintai-prod
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    environment: production
automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fineprintai-cache
  namespace: fineprintai-prod
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
    environment: production
automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fineprintai-vectordb
  namespace: fineprintai-prod
  labels:
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/component: vector-db
    environment: production
automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fineprintai-ai
  namespace: fineprintai-prod
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/component: ai
    environment: production
automountServiceAccountToken: true

---
# Monitoring Service Accounts with enhanced configuration
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: fineprintai-monitoring
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: monitoring-stack
automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: fineprintai-monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: monitoring-stack
automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alertmanager
  namespace: fineprintai-monitoring
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: monitoring-stack
automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki
  namespace: fineprintai-monitoring
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: monitoring-stack
automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail
  namespace: fineprintai-monitoring
  labels:
    app.kubernetes.io/name: promtail
    app.kubernetes.io/component: log-collector
    app.kubernetes.io/part-of: monitoring-stack
automountServiceAccountToken: true

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jaeger
  namespace: fineprintai-monitoring
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/part-of: monitoring-stack
automountServiceAccountToken: true

---
# Cluster Roles
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: server
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]

---
# Cluster Role Bindings
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: fineprintai-monitoring

---
# Application Specific Roles
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: fineprintai
  name: fineprintai-api-role
  labels:
    app.kubernetes.io/name: fineprintai
    app.kubernetes.io/component: api
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: fineprintai
  name: fineprintai-worker-role
  labels:
    app.kubernetes.io/name: fineprintai
    app.kubernetes.io/component: worker
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "create"]

---
# Role Bindings
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fineprintai-api-binding
  namespace: fineprintai
  labels:
    app.kubernetes.io/name: fineprintai
    app.kubernetes.io/component: api
subjects:
  - kind: ServiceAccount
    name: fineprintai-api
    namespace: fineprintai
roleRef:
  kind: Role
  name: fineprintai-api-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fineprintai-worker-binding
  namespace: fineprintai
  labels:
    app.kubernetes.io/name: fineprintai
    app.kubernetes.io/component: worker
subjects:
  - kind: ServiceAccount
    name: fineprintai-worker
    namespace: fineprintai
roleRef:
  kind: Role
  name: fineprintai-worker-role
  apiGroup: rbac.authorization.k8s.io