"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AuditEventType = exports.AuditLevel = void 0;
var AuditLevel;
(function (AuditLevel) {
    AuditLevel["DEBUG"] = "debug";
    AuditLevel["INFO"] = "info";
    AuditLevel["WARN"] = "warn";
    AuditLevel["ERROR"] = "error";
    AuditLevel["CRITICAL"] = "critical";
})(AuditLevel || (exports.AuditLevel = AuditLevel = {}));
var AuditEventType;
(function (AuditEventType) {
    AuditEventType["LOGIN_ATTEMPT"] = "auth.login.attempt";
    AuditEventType["LOGIN_SUCCESS"] = "auth.login.success";
    AuditEventType["LOGIN_FAILURE"] = "auth.login.failure";
    AuditEventType["LOGOUT"] = "auth.logout";
    AuditEventType["PASSWORD_CHANGE"] = "auth.password.change";
    AuditEventType["PASSWORD_RESET_REQUEST"] = "auth.password.reset.request";
    AuditEventType["PASSWORD_RESET_CONFIRM"] = "auth.password.reset.confirm";
    AuditEventType["PASSWORD_EXPIRED"] = "auth.password.expired";
    AuditEventType["TOKEN_ISSUED"] = "auth.token.issued";
    AuditEventType["TOKEN_REFRESHED"] = "auth.token.refreshed";
    AuditEventType["TOKEN_REVOKED"] = "auth.token.revoked";
    AuditEventType["TOKEN_EXPIRED"] = "auth.token.expired";
    AuditEventType["TOKEN_BLACKLISTED"] = "auth.token.blacklisted";
    AuditEventType["SESSION_CREATED"] = "auth.session.created";
    AuditEventType["SESSION_TERMINATED"] = "auth.session.terminated";
    AuditEventType["SESSION_EXPIRED"] = "auth.session.expired";
    AuditEventType["SESSION_SUSPICIOUS"] = "auth.session.suspicious";
    AuditEventType["MFA_SETUP"] = "auth.mfa.setup";
    AuditEventType["MFA_ENABLED"] = "auth.mfa.enabled";
    AuditEventType["MFA_DISABLED"] = "auth.mfa.disabled";
    AuditEventType["MFA_CHALLENGE"] = "auth.mfa.challenge";
    AuditEventType["MFA_SUCCESS"] = "auth.mfa.success";
    AuditEventType["MFA_FAILURE"] = "auth.mfa.failure";
    AuditEventType["MFA_LOCKOUT"] = "auth.mfa.lockout";
    AuditEventType["OAUTH_AUTHORIZATION"] = "auth.oauth.authorization";
    AuditEventType["OAUTH_TOKEN_EXCHANGE"] = "auth.oauth.token_exchange";
    AuditEventType["OAUTH_ACCOUNT_LINK"] = "auth.oauth.account_link";
    AuditEventType["OAUTH_ACCOUNT_UNLINK"] = "auth.oauth.account_unlink";
    AuditEventType["RATE_LIMIT_EXCEEDED"] = "security.rate_limit.exceeded";
    AuditEventType["SUSPICIOUS_ACTIVITY"] = "security.suspicious_activity";
    AuditEventType["BRUTE_FORCE_ATTEMPT"] = "security.brute_force.attempt";
    AuditEventType["IP_BLOCKED"] = "security.ip.blocked";
    AuditEventType["IP_UNBLOCKED"] = "security.ip.unblocked";
    AuditEventType["USER_CREATED"] = "admin.user.created";
    AuditEventType["USER_DELETED"] = "admin.user.deleted";
    AuditEventType["USER_BANNED"] = "admin.user.banned";
    AuditEventType["USER_UNBANNED"] = "admin.user.unbanned";
    AuditEventType["PERMISSIONS_CHANGED"] = "admin.permissions.changed";
    AuditEventType["SYSTEM_STARTUP"] = "system.startup";
    AuditEventType["SYSTEM_SHUTDOWN"] = "system.shutdown";
    AuditEventType["CONFIG_CHANGED"] = "system.config.changed";
    AuditEventType["MAINTENANCE_STARTED"] = "system.maintenance.started";
    AuditEventType["MAINTENANCE_COMPLETED"] = "system.maintenance.completed";
})(AuditEventType || (exports.AuditEventType = AuditEventType = {}));
//# sourceMappingURL=types.js.map