# Prometheus configuration for Fine Print AI Queue System
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'fineprint-queue-monitor'
    environment: 'production'

# Rule files for alerting
rule_files:
  - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  # Fine Print AI Queue System metrics
  - job_name: 'fineprint-queue'
    static_configs:
      - targets: ['queue-system:9090']
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    scheme: http
    params:
      format: ['prometheus']

  # Redis metrics (if redis_exporter is used)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node.js application metrics
  - job_name: 'nodejs'
    static_configs:
      - targets: ['queue-system:3000']
    scrape_interval: 30s
    metrics_path: '/metrics'
    scheme: http

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # System metrics (if node_exporter is available)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

# Alertmanager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Storage configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true

# Remote write/read configurations (for long-term storage)
# remote_write:
#   - url: "https://your-remote-storage/api/v1/write"
#     basic_auth:
#       username: "username"
#       password: "password"

# remote_read:
#   - url: "https://your-remote-storage/api/v1/read"
#     basic_auth:
#       username: "username"
#       password: "password"