---
# Service Account for Prometheus
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: fineprintai-monitoring
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: monitoring

---
# Prometheus ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: monitoring
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  - ingresses
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]

---
# Prometheus ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: fineprintai-monitoring

---
# Service Account for Grafana
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: fineprintai-monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: monitoring

---
# Grafana Role for reading ConfigMaps and Secrets
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grafana
  namespace: fineprintai-monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: monitoring
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]

---
# Grafana RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana
  namespace: fineprintai-monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grafana
subjects:
- kind: ServiceAccount
  name: grafana
  namespace: fineprintai-monitoring

---
# Service Account for Loki
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki
  namespace: fineprintai-monitoring
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: monitoring

---
# Service Account for Promtail
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail
  namespace: fineprintai-monitoring
  labels:
    app.kubernetes.io/name: promtail
    app.kubernetes.io/component: monitoring

---
# Promtail ClusterRole for reading logs
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promtail
  labels:
    app.kubernetes.io/name: promtail
    app.kubernetes.io/component: monitoring
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]

---
# Promtail ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promtail
  labels:
    app.kubernetes.io/name: promtail
    app.kubernetes.io/component: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: promtail
subjects:
- kind: ServiceAccount
  name: promtail
  namespace: fineprintai-monitoring

---
# Service Account for Jaeger
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jaeger
  namespace: fineprintai-monitoring
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/component: monitoring

---
# Service Account for AlertManager
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alertmanager
  namespace: fineprintai-monitoring
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/component: monitoring

---
# Monitoring Admin Role (for troubleshooting)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: monitoring-admin
  namespace: fineprintai-monitoring
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/component: admin
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["extensions"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["networking.k8s.io"]
  resources: ["*"]
  verbs: ["*"]

---
# Monitoring Admin RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitoring-admin
  namespace: fineprintai-monitoring
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/component: admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: monitoring-admin
subjects:
- kind: User
  name: platform-team@fineprintai.com
  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: monitoring-operator
  namespace: fineprintai-monitoring